export const DISPUTE_STATUSES = {
  PENDING: "PENDING",
  REFUND_APPROVED: "REFUND_APPROVED",
  REFUND_REJECTED: "REFUND_REJECTED",
};

export const DISPUTE_STATUS_VALUES = Object.values(DISPUTE_STATUSES);
