export const ORDER_STATUSES = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PENDING_ACCEPTANCE: "PENDING_ACCEPTANCE",
  IN_PROGRESS: "IN_PROGRESS",
  DELIVERED: "DELIVERED",
  REVISION_REQUESTED: "REVISION_REQUESTED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

export const ORDER_STATUS_VALUES = Object.values(ORDER_STATUSES);
