export const PLATFORM_FEE = 10;

export const PAYMENT_STATUSES = {
  PENDING: "PENDING",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  TRANSFERRED: "TRANSFERRED",
  REFUNDED: "REFUNDED",
  CANCELED: "CANCELED",
};

export const PAYMENT_STATUS_VALUES = Object.values(PAYMENT_STATUSES);

export const PAYMENT_EVENT_TYPES = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  AUTHORIZED: "AUTHORIZED",
  CAPTURED: "CAPTURED",
  TRANSFERRED: "TRANSFERRED",
  REFUNDED: "REFUNDED",
  CANCELED: "CANCELED",
  TRANSFER_FAILED: "TRANSFER_FAILED",
};

export const PAYMENT_EVENT_TYPE_VALUES = Object.values(PAYMENT_EVENT_TYPES);
